# Generated by Django 3.0.6 on 2020-07-20 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='itemsFromCategory',
            new_name='selectcategory',
        ),
    ]
