# Generated by Django 3.0.6 on 2020-07-20 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auto_20200720_0558'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=64)),
                ('itemsFromCategory', models.ManyToManyField(blank=True, related_name='itemsFromCategory', to='auctions.Auction')),
            ],
        ),
    ]
